export type Product = {
  id: string;
  name: string;
  weight: number;
  cannabisWeight: number;
  price: number;
  fee: number;
  sku?: string;
  imageURL?: string;
  barcode?: string;
  description?: string;
  cannabisVolume?: number;
  isActive?: number;
  createDate?: Date;
  updateDate?: Date;
  fullProductName?: string;
  productSlug?: string;
  salesPrice: number;
  inventory: number;
  discountAmount: number;
  productscol?: string;
  categories_id: number;
  supplier_id: number;
};

export type ProductItem = {
  pk: string;
  sk: string;
  name: string;
  weight: number;
  cannabisWeight: number;
  price: number;
  fee: number;
  sku?: string;
  imageURL?: string;
  barcode?: string;
  description?: string;
  cannabisVolume?: number;
  isActive?: number;
  createDate?: Date;
  updateDate?: Date;
  fullProductName?: string;
  productSlug?: string;
  salesPrice: number;
  inventory: number;
  discountAmount: number;
  productscol?: string;
  categories_id: number;
  supplier_id: number;
};
